name: modux_generator
description: Move Redux Generator

version: 0.9.0

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  built_value: ^6.4.0
  built_collection: ^4.2.0
  logging: ^0.11.3+2

dev_dependencies:
  analyzer: ^0.35.4
  build: ^1.1.3
  build_runner: ^1.3.1
  build_test: ^0.10.7
  built_value_generator:
    path: ../built-value-generator
#    git: git://github.com/movemedical/built-value-generator
  test: ^1.6.2
  mockito: ^4.0.0
